[package]
name = "mihomo_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"

[lib]
name = "mihomo_rs"
path = "src/lib.rs"